spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_db
    username: postgres
    password: Qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySuperSecretKeyForJwtTokenGeneration1234567890
  expiration: 300000
  refresh-expiration: 604800000

